{% set name = "nme" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nme-{{ version }}.tar.gz
  sha256: 5147dbb795d2d40a1a3b259572b5253b196180e680e3d050acd98a1b73950a9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=3.4
    - setuptools-scm
  run:
    - packaging
    - python >=3.7

test:
  imports:
    - nme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Czaki/nme
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Czaki
