{% set name = "nme" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nme-{{ version }}.tar.gz
  sha256: 7dbda75678da6ab724091f21ab15d605b1bcfc96b8a681bc8999f465f0ef12b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - packaging
    - python >=3.7

test:
  imports:
    - nme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Czaki/nme
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Czaki
