{% set name = "nme" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nme-{{ version }}.tar.gz
  sha256: 9ab20386cd660baed7790e9763f701c921bfe3da163c366833fe0e2fa31bd030

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm >=8
    - setuptools
  run:
    - packaging
    - python >={{ python_min }}
    - local-migrator

test:
  imports:
    - nme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Czaki/nme
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Czaki
