{% set name = "nme" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nme-{{ version }}.tar.gz
  sha256: 9ab20386cd660baed7790e9763f701c921bfe3da163c366833fe0e2fa31bd030

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm >=3.4
    - setuptools-scm
  run:
    - packaging
    - python >=3.8
    - local-migrator

test:
  imports:
    - nme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Czaki/nme
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Czaki
