{% set name = "nme" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nme-{{ version }}.tar.gz
  sha256: 335830b9f662f31ac403fa4d4e7cbd31adc6db3fcec82c5662c8881da889c5c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=3.4
    - setuptools-scm
  run:
    - packaging
    - python >=3.7

test:
  imports:
    - nme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Czaki/nme
  summary: Package for simplify data structures migrations
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Czaki
